name: Build and Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 'lts/*'
          check-latest: true
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
          
      - name: Install dependencies
        run: |
          cd ./frontend
          npm install
          npm install sass
          
      - name: Build
        run: |
          cd ./frontend
          npm run build
          
      - name: Modify files for deployment
        run: |
          cd ./frontend
          mkdir -p ./dist/assets/img
          cp ./src/assets/img/* ./dist/assets/img
          cp ./modifier.py ./dist
          cd ./dist
          python modifier.py
          rm modifier.py
        
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          user_name: Elycts Shaders
          user_email: YoukuShaders@gmail.com
