name: Build and Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.18.0'
          
      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Install dependencies
        run: |
          cd ./frontend
          npm install
          npm install sass
          
      - name: Build
        run: |
          cd ./frontend
          npm run build
          
      - name: Modify files for deployment
        run: |
          cd ./frontend
          mkdir -p ./dist/calculator/assets
          mv ./modifier.py ./dist/calculator
          cd ./dist
          mkdir -p ./calculator/assets
          cd ./assets
          mv ./*.js ../calculator/assets
          mv ./*.css ../calculator/assets
          cd ..
          mv ./index.html ./calculator
          mv ./favicon.ico ./calculator
          cd ./calculator
          python modifier.py
        
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: electron-shaders/electron-shaders.github.io
          publish_dir: ./frontend/dist
          publish_branch: test
          user_name: Elycts Shaders
          user_email: YoukuShaders@gmail.com
          cname: demo.tangzhenwei.com
